title: Made in Armenia
email: your-email@example.com
description: "Уникальные ювелирные изделия ручной работы. Посмотрите наш каталог."
url: "https://demansh.github.io"
baseurl: "/handmade"
default_image: "/assets/images/og-image.jpg"

telegram_username: "username"
instagram_username: "username"
phone_number: "+374 00 000000"

theme: minima
plugins:
  - jekyll-feed

collections:
  products:
    output: true
