- id: 001
  title: "Серебряное кольцо 'Луна'"
  price_num: 4500
  price_display: "4 500 руб."
  description: "Кольцо из серебра 925 пробы с лунным камнем."
  image: "/assets/images/ring-luna.jpg"

- id: 002
  title: "Подвеска 'Звезда'"
  price_num: 3200
  price_display: "3 200 руб."
  description: "Ручная работа, аметист и серебро."
  image: "/assets/images/pendant-star.jpg"

- id: 003
  title: "Серьги 'Капли'"
  price_num: 3900
  price_display: "3 900 руб."
  description: "Минималистичные серьги из золота."
  image: "/assets/images/earrings-drops.jpg"

- id: 004
  title: "Серьги 'Капли'"
  price_num: 3900
  price_display: "3 900 руб."
  description: "Минималистичные серьги из золота."
  image: "/assets/images/earrings-drops.jpg"

- id: 005
  title: "Серьги 'Капли'"
  price_num: 3900
  price_display: "3 900 руб."
  description: "Минималистичные серьги из золота."
  image: "/assets/images/earrings-drops.jpg"

- id: 006
  title: "Серьги 'Капли'"
  price_num: 3900
  price_display: "3 900 руб."
  description: "Минималистичные серьги из золота."
  image: "/assets/images/earrings-drops.jpg"
